version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        HASHICORP_HTTP_VERSION: ${HASHICORP_HTTP_VERSION}
    container_name: backend
    restart: unless-stopped
    networks:
      - app
    mem_limit: 256m

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "${NGINX_PORT}:80"
    depends_on: 
      - backend
    networks:
      - app
    volumes:
      - ./nginx/logs:/var/log/nginx
    mem_limit: 256m
  
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - app
    restart: unless-stopped
    mem_limit: 512m
    
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    networks:
      - app
    restart: unless-stopped
    mem_limit: 256m
    
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:${NGINX_EXPORTER_VERSION}
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - app
    restart: unless-stopped
  
  nginxlog-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:${NGINXLOG_EXPORTER_VERSION}
    container_name: nginxlog-exporter
    restart: unless-stopped
    ports:
      - "4040:4040"
    volumes:
      - ./nginx/logs:/var/log/nginx:ro
      - ./nginx/nginxlog/nginxlog.hcl:/etc/nginxlog/nginxlog.hcl:ro
    command:
      - -config-file=/etc/nginxlog/nginxlog.hcl
    networks:
      - app
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION}
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    networks:
      - app
      
volumes:
  prometheus-data:
  grafana-data:

networks:
  app:
    driver: bridge