{
 "title": "Backend Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Second RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "Total RPS"
    },
    {
     "expr": "sum(rate(app_http_response_count_total{status=~\"2..\", app=\"backend\"}[1m]))",
     "legendFormat": "2xx RPS"
    },
    {
     "expr": "sum(rate(app_http_response_count_total{status=~\"4..\", app=\"backend\"}[1m]))",
     "legendFormat": "4xx RPS"
    },
    {
     "expr": "sum(rate(app_http_response_count_total{status=~\"5..\", app=\"backend\"}[1m]))",
     "legendFormat": "5xx RPS"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU %Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (\r\n  rate(container_cpu_usage_seconds_total{name!=\"\"}[1m])\r\n) / 2 * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (name) (\r\n  rate(container_cpu_cfs_throttled_seconds_total{name!=\"\"}[1m])\r\n) / 2 * 100",
     "legendFormat": "{{label_name}} throttled"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_working_set_bytes{name!=\"\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\"} > 0",
     "legendFormat": "limit {{name}}"
    }
   ]
  }
 ]
}