vars:
  project_dir: /opt/vipservice
  hashicorp_http_version: "1.0.0"
  nginx_version: "1.27.0-alpine"
  nginx_port: "80"
  prometheus_version: "v2.53.0"
  grafana_version: "11.1.0"
  grafana_admin_password: "admin"
  nginx_exporter_version: "1.1.0"
  nginxlog_exporter_version: "v1.11.0"
  cadvisor_version: "v0.47.0"
  backend_mem_limit: "256m"
  nginx_mem_limit: "256m"
  prometheus_mem_limit: "512m"
  grafana_mem_limit: "256m"
  nginx_exporter_mem_limit: "128m"
  nginxlog_exporter_mem_limit: "128m"
  cadvisor_mem_limit: "256m"