datasources:
  - name: prometheus-local
    uid: bfv9j5te82t4wb
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      
  - name: loki
    uid: loki-local
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false