---
- name: Start Docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
    pull: missing
    recreate: auto
    remove_orphans: true
    wait: true
    wait_timeout: 180
  register: compose_up

- name: Get final container status
  command:
    cmd: docker compose -f {{ project_dir }}/docker-compose.yaml ps
  register: compose_ps
  changed_when: false

- name: Show final container status
  debug:
    var: compose_ps.stdout_lines