---
- name: Start Docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
    pull: missing
    recreate: auto
    remove_orphans: true
    wait: true
  register: compose_up

- name: Wait until all containers are running (fail on exited)
  shell: |
    cd {{ project_dir }}

    # Fail fast
    if docker compose ps | awk 'NR>1 && NF>0' | grep -q "Exited"; then
      echo "FATAL: some containers exited:"
      docker compose ps
      exit 2
    fi

    # Wait " Up " services
    not_up=$(docker compose ps | awk 'NR>1 && NF>0' | grep -v " Up " || true)
    if [ -n "$not_up" ]; then
      echo "Not Up yet:"
      echo "$not_up"
      exit 1
    fi

    echo "All containers are Up"
  register: wait_result
  until: wait_result.rc == 0
  failed_when: wait_result.rc == 2
  retries: 30
  delay: 3
  changed_when: false

- name: Get final container status
  command:
    cmd: docker compose -f {{ project_dir }}/docker-compose.yaml ps
  register: compose_ps
  changed_when: false

- name: Show final container status
  debug:
    var: compose_ps.stdout_lines